### ISSUE TITLE
"CreateContainerConfigError: failed to prepare subPath for volumeMount" error with configMap volume

### ISSUE THREAD

**Issue by rendhalver** [coreos/tectonic-forum#290]
## Issue Report Template

I upgraded to 1.8.9 yesterday and I seem to be running into this bug.
kubernetes/kubernetes#61076
It looks to be fixed in 1.8.10. Is there a plan to release that soon?

### Tectonic Version 
1.8.9

### Environment
What hardware/cloud provider/hypervisor is being used with Tectonic?
Bare metal

### Reproduction Steps

  1. ...
  2. ...

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by xytis** [comment]
This bug is critical. Existing deployments are frozen and can not be updated.

**Comment by damosevicius** [comment]
Confirmed, we have the same issue - all deployments are frozen because of this bug.

**Comment by kbrwn** [comment]
AFAIK Tectonic won't publish a fix for this until the next release scheduled in early April. 

hyperkube images exist for 1.8.10

**Comment by rendhalver** [comment]
Ouch.
This got fixed in short order in mainline Tectonic so the fix already exists and shouldn't take long to merge.
Can we please get something done about this?

**Comment by HBO2** [comment]
Hi All, indeed a critical error. I am not amused and think it's ridiculous it is not fixed. All pods with subPath are broken. The only fix is to change the docker version to 17.3.2 and can be done with bash script provide here:
https://gist.github.com/dm0-/66f8375418a8f2369070a2f5902ec5f0

Please note to use  17.03 as version. otherwise this version will not be found

**Comment by lucab** [comment]
I don't personally have any status update to share here, but perhaps @robszumski or @sym3tri do.

**Comment by robszumski** [comment]
Apologies for the trouble this patch caused, it wasn't super well thought out upstream, but it was important to get folks protected from it.

Docker is extremely critical to a Kubernetes cluster and we like to do a lot of testing, scrutinize change logs, etc before pushing out an update. If you'd like to test that out on your cluster using the instructions above, please do report back here.

**Comment by rendhalver** [comment]
Which instructions @robszumski ?
Is there any kind of plan to fix this or do we have to wait till tectonic releases 1.10.x?

**Comment by rendhalver** [comment]
Is this going to get any attention at all?
This is making me seriously consider alternative solutions.

**Comment by robszumski** [comment]
@rendhalver I was referring to the gist posted above: https://gist.github.com/dm0-/66f8375418a8f2369070a2f5902ec5f0

**Comment by rendhalver** [comment]
So that will downgrade or upgrade docker on the nodes?
How do we stop that from getting upgraded afterwards?

**Comment by rendhalver** [comment]
Oh it looks like we have docker 17.3.2 running here.

**Comment by HBO2** [comment]
Hi All, let me explain what I think happened. It's confusing because the actual version of tectonic is packed with docker 17.03 (=17.3.2). So. there is no issue, but ... We also have to deal with Container Linux updates. And what is really an issue is that it updates sometimes separately and in this specific case the update to version STABLE: 1688.5.3 resulted in an update of docker to 17.12.1 (see image:
<img width="1200" alt="screen shot 2018-04-11 at 22 28 14" src="https://user-images.githubusercontent.com/7763328/38641588-c6a31482-3dd7-11e8-9062-4a9f2e1a4b64.png">
I am surprised that a company like Coreos is making mistakes like this. Probably they are to busy to be friends with Red Hat.

Anyhow, when on your cluster the Container Linux updates has runned, you are in trouble when the update managed to update docker too. The only solution is the Gist file and doing in the nodes one by one.
cheers

**Comment by lucab** [comment]
Tectonic manages its own specific container runtime version as mandated by kubernetes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#external-dependencies

Also, this is a regression in k8s which will be fixed by a relevant patch release, regardless of docker version (but I'm not knowledgeable about the timeline).

Also, as noted above in a comment, up-to-date nodes/clusters should already be running with docker 17.03.2.

Also, the gist referenced above is for customizing vanilla ContainerLinux nodes (i.e. not part of tectonic offering), and will likely conflict and break tectonic updates.

**Comment by HBO2** [comment]
@lucab OK, thx for clarifying, but how can you explain that in my cluster there was an update of container linux to STABLE: 1688.5.3 . 
And more important how can I fix the conflicts you referring to. I had no other option to use the gist and get the right docker version (17.03) which is indeed part of 1.8.9-1 The update brought the version of docker to 17.12.1. And resulted in the errors
thx
<img width="670" alt="screen shot 2018-04-11 at 22 52 01" src="https://user-images.githubusercontent.com/7763328/38642668-04f463fa-3ddb-11e8-9005-64dfcfbf4a21.png">

**Comment by rendhalver** [comment]
The Container Linux upgrade hasn't stopped terminating containers from hanging around indefinitely.

**Comment by benlangfeld** [comment]
The versions with which we're having this problem:

![screen shot 2018-04-17 at 14 33 58](https://user-images.githubusercontent.com/210221/38886463-6a26d882-424c-11e8-9312-0b67c4619c82.png)

```
 $ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.6
 Git commit:   2360430
 Built:        Tue Apr  3 05:35:20 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.6
 Git commit:   2360430
 Built:        Tue Apr  3 05:35:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

@robszumski Can you confirm that either Docker 17.09 or Kubernetes 1.8.10 will fix this issue?

**Comment by rendhalver** [comment]
Can we please get some kind of update on this.

**Comment by benlangfeld** [comment]
This issue is the main reason we’re holding off on purchasing Tectonic licenses. It is a strong indication that the product is dead. RedHat is losing serious credibility by creating all of this uncertainty.

**Comment by robszumski** [comment]
Hi folks, apologies for the delay but [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) has been released to the pre-production channel and should fix this issue. Please report back if you do or don't see a change in behavior.

1.9.6 will be pushed to the production channel after baking in pre-prod.

**Comment by rendhalver** [comment]
Can you let us know what will be impacted by this upgrade?
The release notes aren't very specific.
